#!/usr/bin/env bash

COMMANDS=$(cat _docker_cmds | grep "^function" | awk '{print $2}' | grep -v "^_" | tr "\n" " " )

function _debug {
  echo "${DOCKER_IMAGE_NAME}" "${DOCKER_IMAGE_TAG}" "${DOCKER_REPOSITORY}" "${COMMAND}"
}

function _acr_login {
  echo $(az acr login --name ${DOCKER_REPOSITORY})
}

function build {
   cd images/${DOCKER_IMAGE_NAME}
   docker build -t ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG} .
   docker tag ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG} ${DOCKER_REPOSITORY}.azurecr.io/${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}
}

function push {
   _acr_login
  docker push ${DOCKER_REPOSITORY}.azurecr.io/${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}
}