github:
  email: "5db1fee4b5703808c48078a76768b155b421b210c0761cd6a5d223f4d99f1eaa+github-actions[bot]@users.noreply.github.com"
  user: "github-actions"
  branch: "master"
  owner: "jaydoubleu"
  repository: "aks-sds-deploy-copy"
environments:
  - demo
  - dev
  - ithc
  - prod
  - ptlsbox
  - ptl
  - sbox
  - stg
  - test
