# This file contains the additional routes for the application gateway that need to be pinned to a specific Palo.
# Change this IP to 10.11.8.38 to "failover" to the other Palo.
next_hop_address: 10.11.8.37
aks_routes:
  - CGW-Proxy:
    address_prefix: 10.24.1.253/32
  - Interim-Hosting-12:
    address_prefix: 10.23.12.0/22
  - Interim-Hosting-16:
    address_prefix: 10.25.16.0/24
  - JBOX-Prod:
    address_prefix: 10.24.250.0/24
  - DARTS-CPP-SNAT:
    address_prefix: 10.24.0.132/32
  - DARTS-Sites-FITS_2770-Amersham:
    address_prefix: 10.236.81.0/26
  - DARTS-Sites-FITS_0594-Aylesbury:
    address_prefix: 10.1.3.0/24
  - DARTS-Sites-FITS_0024-Barnstaple:
    address_prefix: 10.233.128.0/24
  - DARTS-Sites-FITS_0006-Barrow-In-Furness:
    address_prefix: 10.233.65.0/24
  - DARTS-Sites-FITS_2112-Basildon:
    address_prefix: 10.1.39.0/24
  - DARTS-Sites-FITS_0776-Brimingham-NewtonSt:
    address_prefix: 10.8.19.0/24
  - DARTS-Sites-FITS_1613-Birmingham_Crown:
    address_prefix: 10.2.3.0/24
  - DARTS-Sites-FITS_0176-Bolton_Combined:
    address_prefix: 10.5.35.0/24
  - DARTS-Sites-FITS_0789-Bournemouth_Combined:
    address_prefix: 10.4.2.0/24
  - DARTS-Sites-FITS_0561-Bradford:
    address_prefix: 10.6.13.0/24
  - DARTS-Sites-FITS_0575-Brighton-Mags:
    address_prefix: 10.143.192.0/24
  - DARTS-Sites-FITS_1406-Bristol_Crown:
    address_prefix: 10.4.10.0/24
  - DARTS-Sites-FITS_0177-Burnley:
    address_prefix: 10.5.36.0/24
  - DARTS-Sites-FITS_4260-Caernarfon_Justice_Centre:
    address_prefix: 10.18.140.0/24
  - DARTS-Sites-FITS_0727-Cambridge_Crown_Court:
    address_prefix: 10.1.16.0/24
  - DARTS-Sites-FITS_1579-Canterbury_Combined:
    address_prefix: 10.1.101.0/24
  - DARTS-Sites-FITS_1626-Cardiff:
    address_prefix: 10.3.10.0/24
  - DARTS-Sites-FITS_0174-Carlisle:
    address_prefix: 10.5.37.0/24
  - DARTS-Sites-FITS_0542-Central_Criminal_Court_Old_Bailey:
    address_prefix: 10.1.18.0/24
  - DARTS-Sites-FITS_0687-Chelmsford-Mags:
    address_prefix: 10.142.8.0/24
  - DARTS-Sites-FITS_1278-Chelmsford:
    address_prefix: 10.1.21.0/24
  - DARTS-Sites-FITS_0784-Chester:
    address_prefix: 10.3.15.0/24
  - DARTS-Sites-FITS_0091-Chester-Mags:
    address_prefix: 10.232.196.0/23
  - DARTS-Sites-FITS_1484-Chesterfield:
    address_prefix: 10.233.96.0/23
  - DARTS-Sites-FITS_0158-Coventry:
    address_prefix: 10.2.30.0/24
  - DARTS-Sites-FITS_0719-Croydon:
    address_prefix: 10.1.97.0/32
  - DARTS-Sites-FITS_0163-Derby:
    address_prefix: 10.2.56.0/24
  - DARTS-Sites-FITS_1270-Doncaster:
    address_prefix: 10.6.9.0/24
  - DARTS-Sites-FITS_1269-Durham:
    address_prefix: 10.6.11.0/24
  - DARTS-Sites-FITS_1628-Exeter:
    address_prefix: 10.4.33.0/24
  - DARTS-Sites-FITS_0762-Field-House:
    address_prefix: 10.12.17.0/24
  - DARTS-Sites-FITS_0762-Field-House-A:
    address_prefix: 10.17.144.0/24
  - DARTS-Sites-FITS_0790-Gloucester_Combined:
    address_prefix: 10.8.23.0/24
  - DARTS-Sites-FITS_0564-Great-Grimsby:
    address_prefix: 10.2.57.0/24
  - DARTS-Sites-FITS_1247-Guildford-Mags:
    address_prefix: 10.1.33.0/24
  - DARTS-Sites-FITS_0730-Guildford:
    address_prefix: 10.1.34.0/24
  - DARTS-Sites-FITS_0720-Hatton-Cross:
    address_prefix: 10.7.22.0/24
  - DARTS-Sites-FITS_0550-Hendon_Magistrates:
    address_prefix: 10.232.36.0/23
  - DARTS-Sites-FITS_0715-Harrow:
    address_prefix: 10.1.36.0/24
  - DARTS-Sites-FITS_1607-Hereford:
    address_prefix: 10.18.13.0/24
  - DARTS-Sites-FITS_0143-Hereford-Mags:
    address_prefix: 10.235.8.0/24
  - DARTS-Sites-FITS_1276-Hove:
    address_prefix: 10.1.102.0/24
  - DARTS-Sites-FITS_1706-Huntingdon:
    address_prefix: 10.2.15.0/24
  - DARTS-Sites-FITS_1279-Inner-London:
    address_prefix: 10.1.46.0/24
  - DARTS-Sites-FITS_0722-Ipswich:
    address_prefix: 10.1.48.0/24
  - DARTS-Sites-FITS_0725-Isleworth:
    address_prefix: 10.1.49.0/24
  - DARTS-Sites-FITS_1224-Kidderminster-Mags:
    address_prefix: 10.235.4.0/24
  - DARTS-Sites-FITS_1637-Kingston-Upon-Hull:
    address_prefix: 10.6.35.0/24
  - DARTS-Sites-FITS_1513-Kingston-Upon-Thames:
    address_prefix: 10.1.52.0/24
  - DARTS-Sites-FITS_0565-Leeds:
    address_prefix: 10.6.38.0/24
  - DARTS-Sites-FITS_0159-Leicester:
    address_prefix: 10.2.21.0/24
  - DARTS-Sites-FITS_3706-Leicester_Magistrates:
    address_prefix: 10.232.210.0/23
  - DARTS-Sites-FITS_2422-Loughborough-Mags:
    address_prefix: 10.236.122.0/24
  - DARTS-Sites-FITS_1452-Lewes_Combined:
    address_prefix: 10.1.98.0/24
  - DARTS-Sites-FITS_2435-Lincoln:
    address_prefix: 10.2.66.0/24
  - DARTS-Sites-FITS_0130-Lincoln_Magistrates:
    address_prefix: 10.235.96.0/23
  - DARTS-Sites-FITS_2564-Liverpool-Annex:
    address_prefix: 172.21.6.0/24
  - DARTS-Sites-FITS_2564-Liverpool:
    address_prefix: 10.5.38.0/24
  - DARTS-Sites-FITS_1298_Luton:
    address_prefix: 10.1.62.0/24
  - DARTS-Sites-FITS_0733-Maidstone_Combined:
    address_prefix: 10.1.99.0/24
  - DARTS-Sites-FITS_0244-Manchester-Minshull-St:
    address_prefix: 10.5.18.0/24
  - DARTS-Sites-FITS_0245-Manchester:
    address_prefix: 10.5.16.0/24
  - DARTS-Sites-FITS_1559-Mansfield:
    address_prefix: 10.235.84.0/24
  - DARTS-Sites-FITS_1249-Merthyr-Tydfil:
    address_prefix: 10.3.3.0/24
  - DARTS-Sites-FITS_0571-Mold:
    address_prefix: 10.3.24.0/24
  - DARTS-Sites-FITS_1624-Newcastle_Moot_Hall:
    address_prefix: 10.18.100.0/24
  - DARTS-Sites-FITS_0108-Newcastle_Upon_Tyne:
    address_prefix: 10.6.39.0/24
  - DARTS-Sites-FITS_0256-Newport_Combined_IOW:
    address_prefix: 10.4.34.0/24
  - DARTS-Sites-FITS_1460-Newport_Wales:
    address_prefix: 10.3.28.0/24
  - DARTS-Sites-FITS_1429-Northampton:
    address_prefix: 10.2.58.0/24
  - DARTS-Sites-FITS_0049-North-Somerset:
    address_prefix: 10.4.28.0/24
  - DARTS-Sites-FITS_0049-North-Somerset-A:
    address_prefix: 10.235.148.0/23
  - DARTS-Sites-FITS_0083-Norwich_Combined:
    address_prefix: 10.1.100.0/24
  - DARTS-Sites-FITS_2664-Nottingham_Crown:
    address_prefix: 10.2.59.0/24
  - DARTS-Sites-FITS_1444-Oxford_Combined:
    address_prefix: 10.2.60.0/24
  - DARTS-Sites-FITS_0086-Peterborough-Mags:
    address_prefix: 10.232.160.0/23
  - DARTS-Sites-FITS_1569-Peterborough_Combined:
    address_prefix: 10.2.36.0/24
  - DARTS-Sites-FITS_0787-Plymouth:
    address_prefix: 10.4.35.0/24
  - DARTS-Sites-FITS_0260-Portsmouth:
    address_prefix: 10.4.36.0/24
  - DARTS-Sites-FITS_1433-Preston_Lancaster_Castle:
    address_prefix: 10.18.2.0/24
  - DARTS-Sites-FITS_0123-Preston_Ringway:
    address_prefix: 10.5.39.0/24
  - DARTS-Sites-FITS_0117-Preston_Sessions_House:
    address_prefix: 10.8.17.0/24
  - DARTS-Sites-FITS_0586-Reading-Mags:
    address_prefix: 10.18.150.0/24
  - DARTS-Sites-FITS_0585-Reading_Crown:
    address_prefix: 10.1.72.0/24
  - DARTS-Sites-FITS_0147-Redditch:
    address_prefix: 10.235.12.0/24
  - DARTS-Sites-FITS_1472-Rolls_Building:
    address_prefix: 10.136.64.0/22
  - DARTS-Sites-FITS_1472-Rolls_Building-A:
    address_prefix: 10.136.68.0/23
  - DARTS-Sites-FITS_1418-Salisbury_Combined:
    address_prefix: 10.4.37.0/24
  - DARTS-Sites-FITS_1604-Sheffield_Combined:
    address_prefix: 10.6.40.0/24
  - DARTS-Sites-FITS_0141-Shrewsbury_Crown:
    address_prefix: 10.2.41.0/24
  - DARTS-Sites-FITS_0547-Snaresbrook_Crown:
    address_prefix: 10.1.80.0/24
  - DARTS-Sites-FITS_2097-Southampton_Combined:
    address_prefix: 10.4.38.0/24
  - DARTS-Sites-FITS_1299-Southend:
    address_prefix: 10.1.103.0/24
  - DARTS-Sites-FITS_0740-Southwark:
    address_prefix: 10.1.95.0/24
  - DARTS-Sites-FITS_1614-St_Albans_Crown:
    address_prefix: 10.233.216.0/23
  - DARTS-Sites-FITS_2273-St._Albans_Mags:
    address_prefix: 10.1.77.0/24
  - DARTS-Sites-FITS_0140-Stafford:
    address_prefix: 10.2.61.0/24
  - DARTS-Sites-FITS_0139-Stoke_on_Trent:
    address_prefix: 10.2.62.0/24
  - DARTS-Sites-FITS_1248-Swansea:
    address_prefix: 10.3.35.0/24
  - DARTS-Sites-FITS_0040-Swindon:
    address_prefix: 10.4.39.0/24
  - DARTS-Sites-FITS_1746-Taunton:
    address_prefix: 10.4.40.0/24
  - DARTS-Sites-FITS_0763-Taylor-House:
    address_prefix: 10.17.131.0/24
  - DARTS-Sites-FITS_0763-Taylor-House-A:
    address_prefix: 10.17.132.0/24
  - DARTS-Sites-FITS_1556-Teesside:
    address_prefix: 10.6.41.0/24
  - DARTS-Sites-FITS_0112-Teesside_Magistrates_Court:
    address_prefix: 10.232.228.0/22
  - DARTS-Sites-FITS_0023-Truro:
    address_prefix: 10.4.41.0/24
  - DARTS-Sites-FITS_0087-Warrington:
    address_prefix: 10.3.39.0/24
  - DARTS-Sites-FITS_3965-Warwick_Combined:
    address_prefix: 10.2.65.0/24
  - DARTS-Sites-FITS_0253-Winchester_Combined:
    address_prefix: 10.4.43.0/24
  - DARTS-Sites-FITS_1457-Wolverhampton-Mags:
    address_prefix: 10.232.80.0/24
  - DARTS-Sites-FITS_0166-Wolverhampton_Combined:
    address_prefix: 10.2.63.0/24
  - DARTS-Sites-FITS_0096-Wood_Green_Crown:
    address_prefix: 10.1.91.0/24
  - DARTS-Sites-FITS_0745-Woolwich_Crown:
    address_prefix: 10.1.93.0/24
  - DARTS-Sites-FITS_1516-Worcester:
    address_prefix: 10.2.64.0/24
  - DARTS-Sites-FITS_0708-York_Crown:
    address_prefix: 10.6.37.0/24
  - DARTS-Sites-FITS_0751-RCJ:
    address_prefix: 10.18.40.0/22
  - DARTS-Sites-FITS_0751-RCJ-A:
    address_prefix: 10.18.44.0/22
  - DARTS-Sites-FITS_0236-Stockport_ACTC:
    address_prefix: 10.234.214.0/23
  - DARTS-Sites-ACTC_Cirencester:
    address_prefix: 10.110.209.44/32
  - DARTS-Sites-ACTC-Swansea_ACTC:
    address_prefix: 10.7.27.0/24
  - DARTS-Sites-ACTC_Barbican-AldersgateHse:
    address_prefix: 10.110.209.200/29
  - DARTS-Sites-ACTC_Birmingham-MapleHse:
    address_prefix: 10.110.209.232/29
  - DARTS-Sites-ACTC_Croydon-LeonardoHotel-Ct1:
    address_prefix: 10.110.210.8/29
  - DARTS-Sites-ACTC_Chichester-Ct1:
    address_prefix: 10.110.210.44/32
  - DARTS-Sites-ACTC_Chichester-Ct2:
    address_prefix: 10.110.210.76/32
  - DARTS-Sites-ACTC_Willesden-Ct1:
    address_prefix: 10.110.208.172/32
  - DARTS-Sites-ACTC_Willesden-Ct2:
    address_prefix: 10.110.208.173/32
  - DARTS-Sites-ACTC_Telford:
    address_prefix: 10.110.209.172/32
