name: updatecli

on:
  pull_request:
  workflow_dispatch:
  schedule:
    # Run once a week
    - cron: '0 2 * * 1'  # Every monday at 2am UTC

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  updatecli:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: 11ec3fe1-cfd2-440f-a7a3-034182926fb7
          tenant-id: 6bfc3457-f58c-47de-80dd-56844abea49e
          subscription-id: acb72003-b211-435f-8759-77b8290870b8

      - name: Install Updatecli in the runner
        uses: updatecli/updatecli-action@v2
        with:
          version: v0.33.3

      - name: Run Updatecli in Dry Run mode
        run: updatecli diff --config ./updatecli/weekly.d --values ./updatecli/values.github-action.yaml
        env:
          UPDATECLI_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Updatecli in Apply mode
        if: github.ref == 'refs/heads/master'
        run: updatecli apply --config ./updatecli/weekly.d --values ./updatecli/values.github-action.yaml
        env:
          UPDATECLI_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
